[package]
name = "fs-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "fuzzsoft"
path = "src/main.rs"

[dependencies]
fs-mmu = { path = "../fs-mmu" }
fs-riscv = { path = "../fs-riscv" }
fs-cov = { path = "../fs-cov" }
fs-loader = { path = "../fs-loader" }
fs-platform = { path = "../fs-platform" }

[lints.rust]
unsafe_code = "forbid"
